---
name: Test_collection

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ansible-network/github_actions/.github/actions/checkout_dependency@main

      - name: Run ansible-lint
        uses: ./.github/actions/ansible-lint
  changelog:
    uses: ansible-network/github_actions/.github/workflows/changelog.yml@main
    if: github.event_name != 'schedule'
  sanity:
    uses: ansible-network/github_actions/.github/workflows/sanity.yml@main
  all_green:
    if: ${{ always() && (github.event_name != 'schedule') }}
    needs:
      - ansible-lint
      - changelog
      - sanity
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert 'failure' not in
          set([
          '${{ needs.ansible-lint.result }}',
          '${{ needs.changelog.result }}',
          '${{ needs.sanity.result }}',
          ])"
